baseURL = "https://vinliao.com/"
languageCode = "en-us"
title = "Vincent Liao"
theme = "sam"
	 
# [[params.mainMenu]]
#    link = "/copywriting"
#    text = "I’m a direct response copywriter."
	
[[params.mainMenu]]
    link = "/posts"
    text = "Click here to see my blog/essay"
	
[[params.mainMenu]]
    link = "/about"
    text = "Or here on how to reach me"