baseURL = "https://vinliao.com/"
languageCode = "en-us"
title = "Vincent Liao"
theme = "sam"
	 
# [[params.mainMenu]]
#    link = "/copywriting"
#    text = "I’m a direct response copywriter."
	
[[params.mainMenu]]
    link = "/posts"
    text = "I sometimes write blog and essay."
	
[[params.mainMenu]]
    link = "/about"
    text = "Here’s how you can reach me."