baseURL = "https://vinliao.com/"
languageCode = "en-us"
title = "vinliao"
theme = "ezhil"
paginate = 6

# copyright = "© Copyright notice"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	subtitle = "trying to understand the mind by writing"
	# disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "dark" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:vin@vinliao.com"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/broccoliao"

[taxonomies]
   tag = "tags"
