baseURL = "https://vinliao.com/"
languageCode = "en-us"
title = "vinliao"
theme = "ink"

pagination = 5

[params]
	subtitle = "essays and thoughts"

	# Optional 64x64 avatar image.
 	# avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "Now"
url = "/now"
weight = 2

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/iam_vinliao"